version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:5000/api
        REACT_APP_COGNITO_CLIENT_ID: your-client-id
        REACT_APP_COGNITO_USER_POOL_ID: your-userpool-id
    ports:
      - '3000:80'
    depends_on:
      - backend
    restart: always
